Разработаны базовые классы (абстракции) и классы предметов игры.
Rasseki-Studios/rasseki.game pull request #1
Opened 2018-04-12 14:46 UTC by Moleque

Базовые классы (абстракции): Located, Movable, Item.
Классы предметов: Artifact, Storage, Creature, Hero.

2018-04-15 17:30 UTC, leshiy1295 reviewed
Дополнительно нужно учесть комментарии по этой части из https://github.com/Rasseki-Studios/rasseki.game/pull/2#pullrequestreview-112244767

2018-04-15 17:30 UTC, leshiy1295 commented on Artifact.cpp
> +    this->power = power;
power тоже можно вынести в список инициализации
тут и везде в аналогичных местах

2018-04-15 17:30 UTC, leshiy1295 commented on Storage.cpp
> +        if ((*it).GetId() == id) {
(*it). === it->

2018-04-15 17:30 UTC, leshiy1295 commented on Storage.cpp
> +    for (std::vector<Artifact>::iterator it = artifacts.begin(); it != artifacts.end(); it++) {
лучше использовать auto и range-for
for (auto artifact : artifacts)

2018-04-15 17:30 UTC, leshiy1295 commented on Storage.cpp
> +            artifacts.erase(it);
менять контейнер при проходе по нему - неправильно
нужно вынести удаление из цикла

2018-04-25 10:24 UTC, Moleque reviewed
Замечания исправлены:
- Вынес инициализацию переменных в списки инициализации;
- Избавился от магических констант;
- Переработал метод Move(), разбив его на 2 части (сам алгоритм и оболочка);
- По возможности использовал STL;

2018-04-30 12:40 UTC, leshiy1295 reviewed
Пока новых изменений по текущему модуля мало...

2018-04-30 12:40 UTC, leshiy1295 commented on Movable.cpp
> +    int **map = nullptr;  //картa
почему бы не использовать std::array<std::array>>? размер фиксированный и меняться во времени игры не будет...

2018-04-30 12:40 UTC, leshiy1295 commented on Movable.cpp
> +    int len = wave(map, width, height, destination);
тут же могут быть разные алгоритмы перемещения, кроме волнового
эту часть тоже можно вынести в отдельный интерфейс с отдельной реализацией "волнового" алгоритма.

2018-05-16 01:59 UTC, Moleque reviewed
- Волновой алгоритм выделен в отдельный класс;
- Добавлено взаимодействие с объектом поверхности;
- Создан графический интерфейс с необходимыми формами;
- Реализовано отображение карты и фиксирование нажатия мышки (получение координат);
- Создана статическая библиотека (адаптер) и настроено ее взаимодействие с графическим интерфейсом;

2018-05-31 00:11 UTC, Moleque reviewed
- Настроено корректное взаимодействие с графическим интерфейсом;
- Карта смещается в зависимости от нахождения героя;
- Перемещение героя реализовано в отдельном потоке;
- Добавлен дневник. Данные пишутся из игры с помощью адаптера;
- Данные героя при запуске выводятся в графическом интерфейсе;
- В адаптер добавлены необходимые функции для управления игровым процессом, запуска событий и передачи информации;

2018-06-01 12:32 UTC, leshiy1295 reviewed
По модели - ок
По интерфейсу - много замечаний - основные - это нужно вынести в константы/стили/конфигурацию/ресурсы

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/gamewindow.cpp
> +    QPixmap hero(":/resources/img/hero.png");
через ресурсы

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/gamewindow.cpp
> +    ui->nameHero->setText(data[0].c_str());
выглядит ненадёжно - лучше использовать отдельную структуру из трёх полей

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/gamewindow.cpp
> +    QMessageBox::StandardButton reply = QMessageBox::question(this, "Выход", "Вы действительно хотите выйти в главное меню?", QMessageBox::Yes | QMessageBox::No);
стоит вынести в строковые ресурсы - обычно новый язык переносят в отдельную папку - в коде же используют идентификаторы этих строк. Это позволяет поддержать несколько локализаций

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/gamewindow.ui
> +   <string notr="true">QWidget {
кажется, что лучше всё же стили вынести в отдельный файл

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/gamewindow.ui
> +	background-image: url(&quot;:/resources/img/bground.png&quot;)
стоит не хардкодить внутри, а подставлять снаружи

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/journal.cpp
> +    qDebug() << "hi";
система логирования или убрать

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/journal.cpp
> +    timer = new QTimer();   //инициализируем Таймер
используйте умные указатели

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/journal.cpp
> +        writer += ": ";
кажется, что удобнее всё же работать с промежуточной структурой, а приводить её к строке уже на уровне вывода на экран

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/loadwindow.cpp
> +    QImage bg_window(":/resources/img/bground.png");
сейчас захардкожено - нужно тянуть снаружи из конфигурационного файла

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/main.cpp
> +    QApplication a(argc, argv);
говорили про то, что стоит отвязать main от Qt и сделать отдельный Application

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/mapview.cpp
> +const int offset = 50;
конфиг

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/mapview.cpp
> +    width_end = 1000; //end.x;
все магические константы - в конфиг

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/mapview.cpp
> +    if (x < 0) {
логика дублируется - вынесите в отдельную функцию

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/moc_savewindow.cpp
> +/****************************************************************************
кажется, что этот файл автогенерируемый, и можно его не хранить в репозитории

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/savewindow.cpp
> +    ui->listWidget->addItem("save1");
в константы - в строковый ресурс

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/ui_loadwindow.h
> +        LoadWindow->setStyleSheet(QLatin1String("QWidget {\n"
вынесите в отдельный файл
смешивать код и стилизацию - плохо

2018-06-01 12:32 UTC, leshiy1295 commented on RGI/ui_loadwindow.h
> +        backLoading_2->setText(QApplication::translate("LoadWindow", "\320\235\320\260\320\267\320\260\320\264", 0));
это не читаемо
используйте codec

2018-06-01 12:32 UTC, leshiy1295 commented on libAdapter.cpp
> +        diaryString = "Я иду...";
в константы - в строковый ресурс

2018-06-04 17:44 UTC, Moleque reviewed
Исправление изменений:
- Добавлены конфигурационные файлы: style.h - слили, russian.h - язык, paths.h - пути к ресурсам проекта;
- Добавлены структуры для удобной передачи информации (Message, HeroData);
- Теперь используются умные указатели;
- Удалены файлы, формирующиеся при компиляции.

2018-06-19 14:09 UTC, Moleque reviewed
- Добавлено отображение артефактов, хранящихся у героя;
- Исправлена работа потоков;

2018-06-20 20:48 UTC, leshiy1295 requested changes
Вот тут недодумано, конечно, в одном месте
Но зато много чего посмотрели - и потоки, и локализацию, и конфиг-файлы... Приходите завтра и покажите, что всё, что есть, собранное вместе, работает, и получите баллы за демонстрацию!

2018-06-20 20:48 UTC, leshiy1295 commented on RGI/journal.cpp
> +    Message post = Write();
Journal - не особо понятное, если не вникаться, название для сущности.
Кажется, что это модельная сущность. А на самом деле - графический элемент.
Сам по себе вызов Write из другого модуля - тоже сомнительная затея...

2018-06-21 16:32 UTC, SinimaWath commented on RGI/artifactlist.cpp
> +    timer = std::shared_ptr<QTimer>(new QTimer());   //инициализируем Таймер
есть make_shared<>()

2018-06-21 16:32 UTC, SinimaWath commented on RGI/artifactlist.cpp
> +        for (auto artifact : pack) {
зачем копировать artifact. Можно получать по ссылке const artifact&

2018-06-21 16:32 UTC, SinimaWath commented on RGI/journal.cpp
> +    timer = std::shared_ptr<QTimer>(new QTimer());   //инициализируем Таймер
make_shared<>()

2018-06-21 16:32 UTC, SinimaWath commented on RGI/journal.cpp
> +    connect(timer.get(), SIGNAL(timeout()), this, SLOT(slotWrite()));    //подключаем cлот для отрисовки к таймеру
Используйте новый connect(). Из qt5 https://wiki.qt.io/New_Signal_Slot_Syntax/ru

2018-06-21 16:32 UTC, SinimaWath commented on RGI/journal.cpp
> +    if (post.text != "") {
есть метод empty()

2018-06-21 16:32 UTC, SinimaWath commented on RGI/loadwindow.cpp
> +
Нет реализации в релиз коде. Это будет реализованно?

2018-06-21 16:32 UTC, SinimaWath commented on RGI/mapview.cpp
> +    mapScene = std::shared_ptr<QGraphicsScene>(new QGraphicsScene(this));   //инициализируем сцену для отрисовки
make_shared<>()

2018-06-21 16:32 UTC, SinimaWath commented on movable.cpp
> +        for (int x = 0; x < height; x++) {
Можно попробовать переделать на итераторы. -> будет более гибко

2018-06-21 16:32 UTC, SinimaWath commented on movable.cpp
> +                    for (auto neighbor : neighbors) {   //проходим по всем непомеченным соседям
const auto&

2018-06-21 16:32 UTC, SinimaWath commented on storage.cpp
> +    std::shared_ptr<Artifact> art = artifactsData.getArtifact(id);
Если не ошибаюсь, можно использовать auto

2018-06-21 16:32 UTC, SinimaWath commented on storage.h
> +    std::shared_ptr<Artifact> GetArtifact(std::string);
Возможно, const методы

2018-06-21 16:34 UTC, SinimaWath reviewed
Мелкие замечания. Можно провести небольшой рефакторинг в соответствие с новым стандартом С++

2019-02-13 22:36 UTC, closed without merging